### ISSUE TITLE
Requirements for zcsmower not found: ['pillow==9.5.0'].

### ISSUE THREAD

**Issue by JC38** [ufozone/ha-zcs-mower#18]
Hello,

I have updated HA this morning to the august version and I got this error after restarting it. 
Logger: homeassistant.setup
Source: setup.py:209
First occurred: 07:26:26 (1 occurrences)
Last logged: 07:26:26

Setup failed for custom integration zcsmower: Requirements for zcsmower not found: ['pillow==9.5.0'].

**Comment by JC38** [comment]
Reading the HA release note, it seems they have updated pillow to version 10.0.0
Update Pillow to 10.0.0 ([@frenck](https://github.com/frenck) - [#96106](https://github.com/home-assistant/core/pull/96106))

**Comment by ufozone** [comment]
Fix is available in main branch. Version update is available in two hours or less.

**Comment by ufozone** [comment]
@JC38, new version v0.9.7 is available.
