### ISSUE TITLE
Impossible to connect to server

### ISSUE THREAD

**Issue by lovisgiu** [ufozone/ha-zcs-mower#21]
I tried to use your integration but it does not allow me to connect to server
![image](https://github.com/ufozone/ha-zcs-mower/assets/141752354/81f8b993-12fa-4e68-acd2-2d60bce0de20)
I have inserted client ID but I do not know what to place on Garage Name ... I used Clint Name, robot Name ... no changes

Giuliano

**Comment by ufozone** [comment]
The garage name can be chosen freely.
You got the client key from the mobile app on an iPhone? Unfortunately, all letters are displayed in capital letters, although the key consists of capital and small letters. If you have the opportunity, try using an Android phone. The key is displayed correctly there.

Please activate the integration debug log and try again:
https://github.com/ufozone/ha-zcs-mower#debugging

Then please share the log here to see why no connection is possible.

**Comment by lovisgiu** [comment]
yes I confirm issue was because Iphone change all to capital letters, now it is working! Thanks
