### ISSUE TITLE
Robot starts and back to base immediately 

### ISSUE THREAD

**Issue by alexpelli** [ufozone/ha-zcs-mower#27]
My garden is split in two areas.. when I starts mower from official app it is required to select the area. In HACS app it is not possible to select the area.. this is probably the reason why robots starts and immediately back to the base.

Do you have any idea how to select the cutting area? I have two areas in total.

Thanks

**Comment by alexpelli** [comment]
Thank you very much... I got it and try to set node red commands to integrate with my smart home system.
something is not going well since it is required to indicates the device id.. is this correct:{"device_id":359129025873,"duration":90,"area":1}?

**Comment by ufozone** [comment]
Goto developer-tools > service, in service drop down, choose “ZCS Lawn Mower Robot: Mowing for a certain duration”. See screenshot in my previous post.
Now select your mower from the device drop down list in UI Mode. Click “Edit in YAML” - you will see device_id of this device.
