### ISSUE TITLE
Device-id in node red integration 

### ISSUE THREAD

**Issue by alexpelli** [ufozone/ha-zcs-mower#28]
I'm trying to set node red integration but I cannot understand where to indicate the device_id (work_for service).

![ZCS service](https://github.com/ufozone/ha-zcs-mower/assets/55233863/443ba74a-3e48-48f6-93e2-7c5caa0939c8)

thanks

**Comment by ufozone** [comment]
The device_id is an internal identifier from home assistant for every device (collection of entities) and not easy to find:
https://community.home-assistant.io/t/device-id-entity-id-where-to-find/289230
