### ISSUE TITLE
Stiga A 3000 supported?

### ISSUE THREAD

**Issue by joharei** [ufozone/ha-zcs-mower#32]
Hi, I would like to try your component, but I'm not sure which lawn mower models are supported. How do I know if the robot is based on the ZCS Lawn Mower Robots platform?

**Comment by ufozone** [comment]
Stiga and Zucchetti have been going their separate ways for a few years now.
Your Stiga robot is based on the ZCS platform, if you need/can use the Stiga Autoclip app and the serial number of your robotic mower starts with ST250.... .
