### ISSUE TITLE
0.45 vs 0.44

### ISSUE THREAD

**Issue by JC38** [ufozone/ha-zcs-mower#5]
Hello,

I am new with HA. However, I am trying to understand how it works and this add-on is interesting me.
I have 2 HA for testing, 1 was with the 0.44 version while the other has now the 0.45.
And btw these 2 versions, there are some differences:
![Capture d'écran 2023-05-10 225612](https://github.com/ufozone/ha-zcs-mower/assets/16527222/aa1b1f95-7cd8-4630-8fd4-8aedfe0e660f)
This screenshot above is with the 0.44 : Model is not correct, Brand is ok and  firmware is ok. And three are 4 entities. The control is there and actions seems ok.
The screenshot below is with the 0.45 : Model, brand and firmware are ok. And there are only 3 entities. I lost the control one.
![Capture d'écran 2023-05-10 225551](https://github.com/ufozone/ha-zcs-mower/assets/16527222/951c0011-c8ea-42d4-ac5c-31721ce9538d)
Thank you for your work :-)

**Comment by ufozone** [comment]
Functionally, only the correct mapping of the model name came into the integration. Then I adjusted one more small thing in the localization to the code standard, which has no effect on the entities. All other changes have to do with the management of the integration here on Github (dependencies, workflows).

I can't understand the problem with the missing entity. Please enable the debug log for the integration and restart HA / reload the integration. Post the log here then.

**Comment by JC38** [comment]
The 4th entity came after a while...
![image](https://github.com/ufozone/ha-zcs-mower/assets/16527222/fc89b627-6b35-4818-a97c-1012eb7c6f2e)

There are some wrong translations, like the mower was a vacuum-cleaner.
COMMENCER A NETTOYER should be COMMENCER A TONDRE
Commandes d'aspirateur --> Commandes de tondeuse

**Comment by ufozone** [comment]
Unfortunately, there is no suitable entity type for a lawn mowing robot or at least a generic robot. From my point of view it was and is a wrong decision to include an entity type Vacuum in the Home assistant Core, but not to allow any others (there are some discussions about this in the community).
For this reason, I have used the unsightly workaround like all other integrations for robotic mowers: I use the Vacuum as the control entity.

I cannot influence the translation. A frontend extension would have to be set up here.

Other Lawn Mower integration:
https://github.com/Thomas55555/husqvarna_automower
